// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsSongs = {
  songsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebarsSongs;
